"""
Presentation planning prompt for generating slide structure and content from academic papers.
This version REMOVES the PMRC narrative framework for ablation study purposes.
"""

SLIDES_PLANNING_PROMPT = """
You are an expert academic presentation designer. Your task is to create a comprehensive slide-by-slide presentation plan from the given research paper content.

**Core Objective**: Transform academic paper content into an engaging, well-structured presentation that effectively communicates the research to an academic audience.

**Critical Content Selection Rules:**

- **Table Selection Priority**: 
  * **Table 1**: ALWAYS prioritize - this is typically the main results table
  * **Performance Comparison Tables**: Essential for showing method effectiveness
  * **Ablation Study Tables**: Critical for understanding component contributions
  * **Statistical Significance Tables**: Important for validating claims
- **Figure Selection Strategy**:
  * **Methodology Diagrams**: Must include to explain approach
  * **Results Visualizations**: Charts, graphs showing key findings
  * **Architecture Figures**: System design and flow diagrams
  * **Comparison Plots**: Before/after, baseline vs. proposed
- **Table Integration Strategy**:
  * **Table 1**: Should get its own dedicated slide with detailed analysis
  * **Ablation Studies**: Can be combined with methodology discussion or separate results slide
  * **Additional Tables**: Integrate into relevant sections or create appendix slides if needed

---

### **Academic Presentation Structure**

Organize slides following standard academic presentation conventions.

Please organize slides according to the following structure, **dynamically adapting the number of slides based on paper content richness**. Rich papers with substantial contributions may require 15-25+ slides, while simpler papers may need 10-15 slides. **DO NOT artificially limit presentation length** - prioritize complete content coverage over rigid slide count constraints.

**ADAPTIVE CONTENT EXPANSION GUIDELINES:**
- **Rich Multi-Contribution Papers**: 18-25+ slides (multiple methods, extensive experiments, complex algorithms)
- **Standard Research Papers**: 12-18 slides (single main contribution, standard experimental validation)
- **Short/Workshop Papers**: 8-12 slides (limited scope, preliminary results)
- **Survey/Review Papers**: 15-20+ slides (comprehensive coverage, multiple topics)

**CONTENT RICHNESS INDICATORS:**
- **Expand MORE slides if paper has**: Multiple novel components, extensive ablation studies, complex algorithms, rich experimental analysis, multiple datasets, theoretical contributions
- **Keep STANDARD slides if paper has**: Single main contribution, standard experiments, straightforward methodology
- **Quality over Compression**: Better to have more slides with clear explanations than cramped slides with too much information

**Part 1: Introduction and Background**
1.  **Title Slide (1 slide)**: Include title, authors, and institutional affiliations. (This is automatically generated by LaTeX titlepage, DO NOT create a separate slide for this)
2.  **Introduction & Context (1-2 slides)**:
    *   Introduce the research topic and provide necessary background.
    *   Present the research context and field overview.
    *   **ABSOLUTELY FORBIDDEN**: DO NOT repeat author information, institutional affiliations, conference names, or paper title from the title slide.
    *   **MANDATORY**: Focus on the research area and its current state.
    *   **NO PAPER META-INFO**: Avoid any mention of the specific paper details.
3.  **Problem Statement (1-2 slides)**:
    *   Present the specific research problem being addressed.
    *   Explain the challenges and limitations of existing approaches.
    *   Can show a figure illustrating the problem or existing limitations.

**Part 2: Methodology**
4.  **Approach Overview (1-2 slides)**:
    *   Introduce the proposed method at a high level.
    *   Summarize the main contribution and approach.
    *   Can include a high-level flow diagram or architecture overview.
    *   For complex papers, use 2 slides: overview + contribution summary.

5.  **Detailed Methodology (4-8+ slides, expandable based on complexity)**:
    *   This is the core part of the presentation and needs progressive explanation.
    *   **Architecture/Flow Diagram**: First use one slide to show the overall framework or flow diagram of the method.
    *   **Key Components**: Then use several slides to detail each key module or technical point.
    *   **Rich Content Expansion**: For papers with multiple innovations, dedicate 1-2 slides per major component.
    *   **Algorithm Details**: Include algorithm boxes or pseudocode for complex procedures.
    *   **Technical Innovation**: Highlight what makes your approach different/better.
    *   **Implementation Details**: Include important technical choices and design decisions.

**Part 3: Experimental Validation**
6.  **Experimental Setup (1-2 slides)**:
    *   Describe datasets, evaluation metrics, and experimental configuration.
    *   Include baseline comparisons and evaluation criteria.
    *   **Expandable**: For complex experimental designs, use 2 slides to adequately cover setup details.
7.  **Main Results (3-6+ slides, expandable based on result richness)**:
    *   **Table 1 Presentation**: Dedicate at least one full slide to the main results table (typically Table 1).
    *   **Performance Analysis**: Show quantitative results with clear performance improvements.
    *   **Comparative Analysis**: Compare against state-of-the-art methods with detailed discussion.
    *   **Statistical Significance**: Include error bars, confidence intervals, or significance tests where applicable.
    *   **Rich Result Expansion**: For papers with extensive experiments, create separate slides for different datasets, metrics, or experimental conditions.
8.  **Ablation Studies & Analysis (2-4 slides)**:
    *   **Component Analysis**: Show the contribution of each component to overall performance.
    *   **Design Choice Justification**: Explain why specific design decisions were made.
    *   **Sensitivity Analysis**: Include parameter sensitivity or robustness analysis if available.
    *   **Expandable**: For complex methods with multiple components, dedicate more slides to thorough ablation analysis.

**Part 4: Conclusion and Impact**
9.  **Key Contributions & Summary (1 slide)**:
    *   Summarize the main contributions and key takeaway messages.
    *   Highlight the most significant findings and their implications.
10. **Future Work & Impact (1 slide)**:
    *   Briefly mention future research directions.
    *   Discuss broader impact and potential applications.
11. **Questions & Discussion (1 slide)**:
    *   Create an engaging Q&A slide with "Questions?" or "Discussion" as title.
    *   Include only generic closing statements like "Thank you for your attention!" and "Questions and feedback are welcome."
    *   **DO NOT** include template email addresses or contact placeholders that require manual editing.
12. **Acknowledgments (1 slide)**:
    *   Thank funding agencies, collaborators, advisors, and institutions.
    *   Include funding source logos if available.

----

**Expected Output Format:**

Please provide a detailed JSON structure following this exact format:

```json
[
  {
    "slide_number": 1,
    "title": "Background: Understanding the Research Context",
    "content": [
        "First key point with detailed explanation",
        "Second important aspect with context",
        "Third element connecting to the main theme"
    ],
    "includes_figure": true,
    "figure_reference": "figure_id_from_paper", 
    "includes_table": false,
    "table_reference": null,
    "presenter_notes": "Explain the broader context and establish why this research area matters."
  },
  {
    "slide_number": 2,
    "title": "Problem Statement: Current Challenges",
    "content": [
        "Specific problem definition",
        "Limitations of existing approaches", 
        "Gap that this research addresses"
    ],
    "includes_figure": false,
    "figure_reference": null,
    "includes_table": false,
    "table_reference": null,
    "presenter_notes": "Clearly articulate the research problem and motivate the need for a solution."
  },
  {
    "slide_number": 3,
    "title": "Our Approach: Method Overview",
    "content": [
        "High-level description of the proposed method",
        "Key innovation and contributions",
        "Overall workflow and architecture"
    ],
    "includes_figure": true,
    "figure_reference": "method_diagram_figure_id",
    "includes_table": false,
    "table_reference": null,
    "presenter_notes": "Provide clear overview of the approach before diving into technical details."
  },
  {
    "slide_number": 4,
    "title": "Experimental Results",
    "content": [
        "Performance comparison with baselines",
        "Statistical significance of improvements",
        "Key findings and observations"
    ],
    "includes_figure": false,
    "figure_reference": null,
    "includes_table": true,
    "table_reference": "table1",
    "table_data": {
        "id": "table1", 
        "title": "Table 1: Performance comparison...",
        "markdown_content": "| Method | Accuracy | F1-Score |..."
    },
    "presenter_notes": "Highlight the significant improvements achieved by the proposed method."
  },
  {
    "slide_number": 5,
    "title": "Ablation Study: Component Analysis",
    "content": [
        "Impact of removing key components",
        "Contribution of each module to overall performance",
        "Design choice validation"
    ],
    "includes_figure": false,
    "figure_reference": null,
    "includes_table": true,
    "table_reference": "ablation_table",
    "table_data": {
        "id": "ablation_table",
        "title": "Table 2: Ablation study results...",
        "markdown_content": "| Configuration | Performance | Change |..."
    },
    "presenter_notes": "Demonstrate the necessity and contribution of each component."
  },
  {
    "slide_number": 6,
    "title": "Conclusion and Future Work",
    "content": [
        "Summary of key contributions",
        "Broader impact and applications",
        "Future research directions"
    ],
    "includes_figure": false,
    "figure_reference": null,
    "includes_table": false,
    "table_reference": null,
    "presenter_notes": "Summarize key contributions and inspire future research directions."
  },
  {
    "slide_number": 7,
    "title": "Questions & Discussion",
    "content": [
        "Thank you for your attention!",
        "Questions and feedback are welcome."
    ],
    "includes_figure": false,
    "figure_reference": null,
    "includes_table": false,
    "table_reference": null,
    "presenter_notes": "Encourage audience engagement and discussion."
  }
]
```

**Key Requirements Summary:**

1. **Content Quality**: Each slide should have substantive, detailed content - not just bullet point outlines.
2. **Figure Integration**: Reference actual figures from the paper using their IDs. Include figure when it enhances understanding.
3. **Table Integration**: Include important tables (especially Table 1) with their complete markdown content for proper LaTeX rendering.
4. **Presenter Notes**: Provide detailed guidance for each slide to help with presentation delivery.
5. **Adaptive Length**: Adjust the number of slides based on content richness - don't artificially limit to a fixed number.

**UNIQUE FIGURE ASSIGNMENT RULES:**
- **Track Used Figures**: Keep a mental record of which figures have been assigned to slides
- **Priority Assignment**: 
  1. **Methodology slides**: Get first pick of relevant architecture/flow diagrams
  2. **Results slides**: Get priority for experimental result visualizations  
  3. **Problem slides**: Get priority for problem illustration figures
  4. **Background slides**: Get remaining contextual figures
- **NO REPETITION**: Once a figure is assigned to a slide, it cannot appear on any other slide
- **One Figure Per Slide**: Each slide should include at most one figure to maintain clarity
- **Quality over Quantity**: Better to have fewer slides with well-matched figures than many slides with repeated or poorly matched figures

**INTELLIGENT TABLE SELECTION & PROCESSING RULES:**

1. **Priority Hierarchy** (in order):
   - **Table 1**: ALWAYS include if it exists - typically contains main experimental results
   - **Ablation Study Tables**: Critical for understanding method components
   - **Comparison Tables**: Essential for competitive analysis
   - **Statistical Analysis Tables**: Important for validation

2. **Table Processing Requirements**:
   - **Complete Markdown**: Include full table structure, not summaries
   - **Preserve Formatting**: Maintain column headers, group headers, statistical indicators
   - **Data Integrity**: Ensure all numbers, symbols, and formatting are preserved exactly
   - **Caption Integration**: Include complete table titles and any relevant captions

3. **Table-Slide Matching**:
   - **Dedicated Table Slides**: Main results tables (especially Table 1) get their own slides
   - **Integrated Tables**: Smaller tables can be combined with explanatory content
   - **Context Preservation**: Ensure table content matches the slide's narrative focus

**CONTENT OVERFLOW PREVENTION RULES:**

1. **Content Density Assessment**:
   - **Light Content** (1-2 bullet points): Can accommodate large figures/tables
   - **Medium Content** (3-4 bullet points): Requires moderate figure/table sizing
   - **Heavy Content** (5+ bullet points): Needs compact figures or content splitting

2. **Smart Content Splitting**:
   - **Large Tables**: Split complex tables across multiple slides by row groups or metrics
   - **Complex Figures**: Use zoomed sections or step-by-step reveals for detailed diagrams
   - **Dense Content**: Break comprehensive topics into focused sub-slides

3. **Dynamic Spacing Optimization**:
   - **Bullet Spacing**: Adjust itemsep based on content volume
   - **Figure Sizing**: Scale images based on available space and content density
   - **Table Formatting**: Use compact spacing for large tables, standard for smaller ones

**CONTENT REDUNDANCY ELIMINATION RULES:**

1. **Slide-Level Deduplication**:
   - **Unique Value Requirement**: Each slide must provide distinct information
   - **Content Overlap Check**: Verify no two slides cover identical concepts
   - **Progressive Detail**: Later slides should build upon, not repeat, earlier content

2. **Cross-Slide Content Coordination**:
   - **Information Progression**: Ensure logical flow without redundant repetition
   - **Reference Integration**: Use "as mentioned earlier" when building on previous content
   - **Complementary Focus**: Each slide should have a unique angle or aspect

3. **Redundancy Detection Examples**:
  * If slide A describes "NeRF as 5D function", slide B cannot repeat "NeRF represents scenes as 5D function"
  * If slide A covers "applications in VR/AR", slide B cannot mention the same applications again
- **CONSOLIDATION MANDATORY**: If two slides have overlapping content, merge them into one comprehensive slide
- **DISTINCT VALUE RULE**: Every slide must answer "What NEW information does this slide provide that previous slides don't?"

**CRITICAL FIGURE-TEXT MATCHING RULES:**

1. **Semantic Alignment**:
   - **Topic Matching**: Figure content must directly relate to slide's main topic
   - **Level Matching**: Technical depth of figure should match slide content complexity
   - **Purpose Matching**: Figure should serve the slide's specific educational or persuasive goal

2. **Content-Figure Synergy**:
   - **Supporting Evidence**: Figures should provide visual evidence for textual claims
   - **Explanatory Power**: Complex concepts in text should be clarified by corresponding figures
   - **Narrative Integration**: Figures should feel like natural extensions of the slide content, not decorations

3. **Matching Quality Examples**:
   - **GOOD**: Architecture diagram on methodology slide, results chart on performance slide
   - **BAD**: Random algorithm flowchart on conclusion slide, unrelated dataset visualization on problem statement slide

**CRITICAL REMINDER ON SLIDE COUNT:**
- **DO NOT** artificially constrain the number of slides based on the JSON example
- **MANDATORY**: Rich research papers REQUIRE comprehensive coverage - aim for 15-25+ slides for substantial contributions
- **Example Guidance**: The 8-slide example above is a MINIMUM template - most academic papers need 2-3x more slides for proper coverage
- **Quality Expectation**: Each major contribution, experimental result, and methodological component should get adequate slide coverage

Please strictly follow the above requirements and output only the detailed slides_plan with structured content for every slide, not just ideas.

Please start working now.
"""
